# Generated by Django 4.2.9 on 2025-11-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to crawl', max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_links', models.IntegerField(default=0)),
                ('internal_links', models.IntegerField(default=0)),
                ('external_links', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('page_size', models.IntegerField(help_text='Page size in bytes')),
                ('crawl_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_info', to='crawler.crawljob')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('link_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('anchor_text', models.CharField(blank=True, max_length=500)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('is_broken', models.BooleanField(default=False)),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crawler.crawljob')),
            ],
            options={
                'ordering': ['link_type', 'url'],
            },
        ),
    ]
