# Generated by Django 4.2.9 on 2025-11-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='parent_element',
            field=models.CharField(blank=True, help_text='Parent HTML element (header, footer, nav, etc.)', max_length=100),
        ),
    ]
