# Generated by Django 4.2.9 on 2025-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_link_parent_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='parent_element',
            field=models.CharField(blank=True, help_text='Parent HTML element (header, footer, nav, etc.)', max_length=100, null=True),
        ),
    ]
