# Generated by Django 4.2.9 on 2025-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_link_parent_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='html_structure',
            field=models.JSONField(blank=True, help_text='HTML semantic structure as JSON', null=True),
        ),
    ]
