# Generated by Django 4.2.9 on 2025-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_pageinfo_html_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='schema_markup',
            field=models.JSONField(blank=True, help_text='JSON-LD schema markup data', null=True),
        ),
    ]
