# Generated by Django 4.2.9 on 2025-11-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_pageinfo_schema_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='lighthouse_score',
            field=models.JSONField(blank=True, help_text='Google Lighthouse performance audit results', null=True),
        ),
    ]
